/*
 * This file is generated by jOOQ.
 */
package org.example.template.domain.db;


import org.example.template.domain.db.tables.FlywaySchemaHistory;
import org.example.template.domain.db.tables.Template;
import org.example.template.domain.db.tables.records.FlywaySchemaHistoryRecord;
import org.example.template.domain.db.tables.records.TemplateRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<TemplateRecord> TEMPLATE_PKEY = Internal.createUniqueKey(Template.TEMPLATE, DSL.name("template_pkey"), new TableField[] { Template.TEMPLATE.ID }, true);
}
