/*
 * This file is generated by jOOQ.
 */
package org.example.template.domain.db;


import org.example.template.domain.db.tables.FlywaySchemaHistory;
import org.example.template.domain.db.tables.Template;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.template</code>.
     */
    public static final Template TEMPLATE = Template.TEMPLATE;
}
